import { CodeChefUser } from "../types/codechef-user";
import { CodeForcesUser } from "../types/codeforces-user";

// https://codeforces.com/api/user.info?handles=ahammed.sabuj_;abdul_lah;phitron_batch_3;aminul_dola;Arjun_UiU;Arup_43;asif_abdullah;Atik203;ramim-ahmed;aushamim;UnSolvedBug_Farhan;HaqueWasif;hasan_dev04;Hironmoy_Ray;imran_258;_BigHero;Fazly-Fardin;mjony;Jubayer__Hossain;kaium2020;kausar0.5;Khushnor_Rahman_Meem;Ayirbik;labib1204;mdmahabub55;Mahbub_Turza;mahmudqudrati;Masud_Abdullah;Hossain0012;mdalifahmed114510;hasan_03;learnerminj;Heisenburg-120;_Grandmaster;Md-Merazul-Islam;mehadi40758;mohiuddin_sizan;MOIN46;Morshed_Alam33;Mubarak_Hossain;muhammad_sayem;BLACK-HEAD;nasimahemd0909;MD.Naerullah;niloy097;niloymahmudapu;onceuponnion_9;-11;Black_Pencil;rakibulhassan29052000;ratulhasan2108;Rayhan_03;sanzidtonu;RiadMEhedi;robot_riad;Rocky20809;rollno_infinity;S.Popy;sadif609;samiunblack;SSKsan;schrodingersmile;shafaitzaman1234;shafiq1st;makmodol1173;sharif_dupharma;Mistake_factory;CRYP70N1C;BugBane_Hridoy;b14ckb3rry;soaib056;Soumick;srayosikder;sumit_chandra;Sunjida_Akter;SyedaGulnaj;tahdiislam;tahsin005;talatmcc;voidd_nulll
export const codeForcesUsers: CodeForcesUser[] = [
    {
        lastName: "Ahammed",
        country: "Bangladesh",
        lastOnlineTimeSeconds: 1697126464,
        city: "Sirajganj",
        rating: 574,
        friendOfCount: 20,
        titlePhoto: "https://userpic.codeforces.org/2595061/title/ec179db6ff5064e4.jpg",
        handle: "ahammed.sabuj_",
        avatar: "https://userpic.codeforces.org/2595061/avatar/4f96eda6efb35a88.jpg",
        firstName: "Md. Sabuj",
        contribution: 0,
        organization: "IIT,Jahangirnagar University",
        rank: "newbie",
        maxRating: 859,
        registrationTimeSeconds: 1653287388,
        maxRank: "newbie"
    },
    {
        contribution: 0,
        lastOnlineTimeSeconds: 1695540124,
        friendOfCount: 2,
        titlePhoto: "https://userpic.codeforces.org/2729107/title/f6a6d9c3d1b4d75f.jpg",
        handle: "abdul_lah",
        avatar: "https://userpic.codeforces.org/2729107/avatar/7f55d2852b20dc75.jpg",
        registrationTimeSeconds: 1660724100
    },
    {
        firstName: "Alamgir",
        lastName: "Hossain",
        country: "Bangladesh",
        contribution: 0,
        lastOnlineTimeSeconds: 1697113769,
        city: "Dhaka",
        organization: "ISTT(Institute of Science, Trade, and Technology)",
        friendOfCount: 2,
        titlePhoto: "https://userpic.codeforces.org/3192188/title/1ce61cbfcb660b3c.jpg",
        handle: "phitron_batch_3",
        avatar: "https://userpic.codeforces.org/3192188/avatar/3b1cb0c703d38275.jpg",
        registrationTimeSeconds: 1681045329
    },
    {
        contribution: 0,
        lastOnlineTimeSeconds: 1697122889,
        friendOfCount: 2,
        titlePhoto: "https://userpic.codeforces.org/no-title.jpg",
        handle: "aminul_dola",
        avatar: "https://userpic.codeforces.org/no-avatar.jpg",
        registrationTimeSeconds: 1681410205
    },
    {
        contribution: 0,
        lastOnlineTimeSeconds: 1697130836,
        friendOfCount: 2,
        titlePhoto: "https://userpic.codeforces.org/no-title.jpg",
        handle: "Arjun_UiU",
        avatar: "https://userpic.codeforces.org/no-avatar.jpg",
        registrationTimeSeconds: 1681039996
    },
    {
        lastName: "Debnath",
        country: "Bangladesh",
        lastOnlineTimeSeconds: 1697092966,
        city: "Dhaka",
        rating: 891,
        friendOfCount: 13,
        titlePhoto: "https://userpic.codeforces.org/1429612/title/7ab8382ca078c97d.jpg",
        handle: "Arup_43",
        avatar: "https://userpic.codeforces.org/1429612/avatar/6eb2fe6a3434705.jpg",
        firstName: "Arup",
        contribution: 0,
        organization: "BUET(Dhaka,Bangladesh)",
        rank: "newbie",
        maxRating: 1382,
        registrationTimeSeconds: 1583567126,
        maxRank: "pupil"
    },
    {
        lastName: "Abdullah",
        country: "Bangladesh",
        lastOnlineTimeSeconds: 1697116247,
        city: "Dhaka",
        rating: 887,
        friendOfCount: 40,
        titlePhoto: "https://userpic.codeforces.org/2742723/title/feaad958fb5b9e87.jpg",
        handle: "asif_abdullah",
        avatar: "https://userpic.codeforces.org/2742723/avatar/bcf2592333eab026.jpg",
        firstName: "Asif",
        contribution: 0,
        organization: "Bangladesh University of Business and Technology",
        rank: "newbie",
        maxRating: 989,
        registrationTimeSeconds: 1661504084,
        maxRank: "newbie"
    },
    {
        lastName: "Rahaman",
        country: "Bangladesh",
        lastOnlineTimeSeconds: 1697133496,
        city: "Dhaka",
        rating: 961,
        friendOfCount: 3,
        titlePhoto: "https://userpic.codeforces.org/no-title.jpg",
        handle: "Atik203",
        avatar: "https://userpic.codeforces.org/no-avatar.jpg",
        firstName: "Md.Atikur",
        contribution: 0,
        organization: "United International University",
        rank: "newbie",
        maxRating: 961,
        registrationTimeSeconds: 1672818425,
        maxRank: "newbie"
    },
    {
        lastName: "Ahmed",
        country: "Bangladesh",
        lastOnlineTimeSeconds: 1697135981,
        city: "Sylhet",
        rating: 790,
        friendOfCount: 12,
        titlePhoto: "https://userpic.codeforces.org/3185751/title/dfc234d2c096a631.jpg",
        handle: "ramim-ahmed",
        avatar: "https://userpic.codeforces.org/3185751/avatar/e445f86d299a3ac5.jpg",
        firstName: "Ramim",
        contribution: 0,
        organization: "Metropolitan University , Sylhet , Bangladesh",
        rank: "newbie",
        maxRating: 798,
        registrationTimeSeconds: 1680710051,
        maxRank: "newbie"
    },
    {
        firstName: "Amjad Uddin",
        lastName: "Shamim",
        country: "Bangladesh",
        contribution: 0,
        lastOnlineTimeSeconds: 1697124788,
        city: "Dhaka",
        organization: "Daffodil International Univarsity",
        friendOfCount: 4,
        titlePhoto: "https://userpic.codeforces.org/3192347/title/890606656a30e281.jpg",
        handle: "aushamim",
        avatar: "https://userpic.codeforces.org/3192347/avatar/a67a5b45450374a0.jpg",
        registrationTimeSeconds: 1681049192
    },
    {
        country: "Bangladesh",
        lastOnlineTimeSeconds: 1697116195,
        city: "Dhaka",
        rating: 1085,
        friendOfCount: 29,
        titlePhoto: "https://userpic.codeforces.org/no-title.jpg",
        handle: "UnSolvedBug_Farhan",
        avatar: "https://userpic.codeforces.org/no-avatar.jpg",
        contribution: 0,
        organization: "Bangladesh University of Business and Technology",
        rank: "newbie",
        maxRating: 1085,
        registrationTimeSeconds: 1687811363,
        maxRank: "newbie"
    },
    {
        lastName: "Haque",
        country: "Bangladesh",
        lastOnlineTimeSeconds: 1697117387,
        city: "Dhaka",
        rating: 777,
        friendOfCount: 4,
        titlePhoto: "https://userpic.codeforces.org/no-title.jpg",
        handle: "HaqueWasif",
        avatar: "https://userpic.codeforces.org/no-avatar.jpg",
        firstName: "Wasiful",
        contribution: 0,
        organization: "App. Math,University of Dhaka",
        rank: "newbie",
        maxRating: 777,
        registrationTimeSeconds: 1674382571,
        maxRank: "newbie"
    },
    {
        firstName: "Hasanuzzaman",
        lastName: "Hasan",
        country: "Bangladesh",
        contribution: 0,
        lastOnlineTimeSeconds: 1697126127,
        organization: "",
        friendOfCount: 2,
        titlePhoto: "https://userpic.codeforces.org/no-title.jpg",
        handle: "hasan_dev04",
        avatar: "https://userpic.codeforces.org/no-avatar.jpg",
        registrationTimeSeconds: 1680971237
    },
    {
        firstName: "Hironmoy",
        lastName: "Ray",
        country: "Bangladesh",
        contribution: 0,
        lastOnlineTimeSeconds: 1696860948,
        city: "Rangpur City",
        organization: "Begum Rokeya University, Rangpur",
        friendOfCount: 4,
        titlePhoto: "https://userpic.codeforces.org/3166955/title/d718db3213e5eca8.jpg",
        handle: "Hironmoy_Ray",
        avatar: "https://userpic.codeforces.org/3166955/avatar/270cf2317258ae05.jpg",
        registrationTimeSeconds: 1679722225
    },
    {
        lastName: "Hasan",
        lastOnlineTimeSeconds: 1697121523,
        rating: 855,
        friendOfCount: 7,
        titlePhoto: "https://userpic.codeforces.org/no-title.jpg",
        handle: "imran_258",
        avatar: "https://userpic.codeforces.org/no-avatar.jpg",
        firstName: "Imran",
        contribution: 0,
        organization: "",
        rank: "newbie",
        maxRating: 855,
        registrationTimeSeconds: 1680987252,
        maxRank: "newbie"
    },
    {
        lastName: "Uddin",
        country: "Bangladesh",
        lastOnlineTimeSeconds: 1697133644,
        city: "Chittagong",
        rating: 1146,
        friendOfCount: 8,
        titlePhoto: "https://userpic.codeforces.org/no-title.jpg",
        handle: "_BigHero",
        avatar: "https://userpic.codeforces.org/no-avatar.jpg",
        firstName: "Ishtiaq",
        contribution: 0,
        organization: "",
        rank: "newbie",
        maxRating: 1155,
        registrationTimeSeconds: 1667647903,
        maxRank: "newbie"
    },
    {
        contribution: 0,
        lastOnlineTimeSeconds: 1697114824,
        rating: 1056,
        friendOfCount: 3,
        titlePhoto: "https://userpic.codeforces.org/no-title.jpg",
        rank: "newbie",
        handle: "Fazly-Fardin",
        maxRating: 1392,
        avatar: "https://userpic.codeforces.org/no-avatar.jpg",
        registrationTimeSeconds: 1517233545,
        maxRank: "pupil"
    },
    {
        firstName: "Md. Manjurul Hoque",
        lastName: "Jony",
        contribution: 0,
        lastOnlineTimeSeconds: 1697121360,
        organization: "",
        friendOfCount: 2,
        titlePhoto: "https://userpic.codeforces.org/3190813/title/508b5fadf2187197.jpg",
        handle: "mjony",
        avatar: "https://userpic.codeforces.org/3190813/avatar/f5d61d1db0220160.jpg",
        registrationTimeSeconds: 1680974996
    },
    {
        contribution: 0,
        lastOnlineTimeSeconds: 1697124337,
        rating: 348,
        friendOfCount: 5,
        titlePhoto: "https://userpic.codeforces.org/no-title.jpg",
        rank: "newbie",
        handle: "Jubayer__Hossain",
        maxRating: 348,
        avatar: "https://userpic.codeforces.org/no-avatar.jpg",
        registrationTimeSeconds: 1654011844,
        maxRank: "newbie"
    },
    {
        lastName: "Uddin",
        country: "Bangladesh",
        lastOnlineTimeSeconds: 1696942170,
        city: "Chittagong",
        rating: 823,
        friendOfCount: 8,
        titlePhoto: "https://userpic.codeforces.org/no-title.jpg",
        handle: "kaium2020",
        avatar: "https://userpic.codeforces.org/no-avatar.jpg",
        firstName: "Kaium",
        contribution: 0,
        organization: "Port City International University",
        rank: "newbie",
        maxRating: 952,
        registrationTimeSeconds: 1576822939,
        maxRank: "newbie"
    },
    {
        country: "Bangladesh",
        lastOnlineTimeSeconds: 1697120982,
        city: "Rajshahi",
        rating: 839,
        friendOfCount: 6,
        titlePhoto: "https://userpic.codeforces.org/3361565/title/6ec23a595bd5f746.jpg",
        handle: "kausar0.5",
        avatar: "https://userpic.codeforces.org/3361565/avatar/42fe8efb265e6f1a.jpg",
        contribution: 0,
        organization: "Begum Rokeya University, Rangpur",
        rank: "newbie",
        maxRating: 856,
        registrationTimeSeconds: 1690272058,
        maxRank: "newbie"
    },
    {
        contribution: 0,
        lastOnlineTimeSeconds: 1697117345,
        friendOfCount: 2,
        titlePhoto: "https://userpic.codeforces.org/no-title.jpg",
        handle: "Khushnor_Rahman_Meem",
        avatar: "https://userpic.codeforces.org/no-avatar.jpg",
        registrationTimeSeconds: 1659684565
    },
    {
        firstName: "Md. Golam",
        lastName: "Kibria",
        country: "Bangladesh",
        contribution: 0,
        lastOnlineTimeSeconds: 1697121712,
        city: "Comilla",
        organization: "",
        friendOfCount: 2,
        titlePhoto: "https://userpic.codeforces.org/3002114/title/c7ae1f83aa6f4197.jpg",
        handle: "Ayirbik",
        avatar: "https://userpic.codeforces.org/3002114/avatar/73e0a3f7452a6351.jpg",
        registrationTimeSeconds: 1672754117
    },
    {
        contribution: 0,
        lastOnlineTimeSeconds: 1697126229,
        friendOfCount: 1,
        titlePhoto: "https://userpic.codeforces.org/no-title.jpg",
        handle: "labib1204",
        avatar: "https://userpic.codeforces.org/no-avatar.jpg",
        registrationTimeSeconds: 1695532582
    },
    {
        contribution: 0,
        lastOnlineTimeSeconds: 1697092261,
        rating: 350,
        friendOfCount: 3,
        titlePhoto: "https://userpic.codeforces.org/3192089/title/2e7fb23a194f86e4.jpg",
        rank: "newbie",
        handle: "mdmahabub55",
        maxRating: 350,
        avatar: "https://userpic.codeforces.org/3192089/avatar/c658e0ffb0557dd4.jpg",
        registrationTimeSeconds: 1681040480,
        maxRank: "newbie"
    },
    {
        lastName: "Turza",
        country: "Bangladesh",
        lastOnlineTimeSeconds: 1696756900,
        city: "Dhaka",
        rating: 1130,
        friendOfCount: 24,
        titlePhoto: "https://userpic.codeforces.org/2474255/title/5595662cc7ae23b7.jpg",
        handle: "Mahbub_Turza",
        avatar: "https://userpic.codeforces.org/2474255/avatar/af92a58b2e9f7ce6.jpg",
        firstName: "Mahbub Ahmed",
        contribution: 0,
        organization: "North South University",
        rank: "newbie",
        maxRating: 1256,
        registrationTimeSeconds: 1646119736,
        email: "imahbubturza@gmail.com",
        maxRank: "pupil"
    },
    {
        lastName: "Qudrati",
        country: "Bangladesh",
        lastOnlineTimeSeconds: 1697119531,
        city: "Sylhet",
        rating: 743,
        friendOfCount: 5,
        titlePhoto: "https://userpic.codeforces.org/2892998/title/362975af02ef17ac.jpg",
        handle: "mahmudqudrati",
        avatar: "https://userpic.codeforces.org/2892998/avatar/6f6d71267276324c.jpg",
        firstName: "Mahmudul Haque",
        contribution: 0,
        organization: "Metropolitan University , Sylhet , Bangladesh",
        rank: "newbie",
        maxRating: 743,
        registrationTimeSeconds: 1668002731,
        maxRank: "newbie"
    },
    {
        lastName: "Abdullah",
        country: "Bangladesh",
        lastOnlineTimeSeconds: 1697120319,
        city: "Dhaka",
        rating: 971,
        friendOfCount: 39,
        titlePhoto: "https://userpic.codeforces.org/no-title.jpg",
        handle: "Masud_Abdullah",
        avatar: "https://userpic.codeforces.org/no-avatar.jpg",
        firstName: "Masud",
        contribution: 0,
        organization: "Bangladesh University of Business and Technology",
        rank: "newbie",
        maxRating: 971,
        registrationTimeSeconds: 1665168989,
        maxRank: "newbie"
    },
    {
        lastName: "Hossain",
        country: "Bangladesh",
        lastOnlineTimeSeconds: 1697116721,
        city: "Comilla",
        rating: 827,
        friendOfCount: 14,
        titlePhoto: "https://userpic.codeforces.org/no-title.jpg",
        handle: "Hossain0012",
        avatar: "https://userpic.codeforces.org/no-avatar.jpg",
        firstName: "Md. Nayeem",
        contribution: 0,
        organization: "Sylhet Engineering College",
        rank: "newbie",
        maxRating: 860,
        registrationTimeSeconds: 1678348538,
        email: "m.n.hossain0012@gmail.com",
        maxRank: "newbie"
    },
    {
        contribution: 0,
        lastOnlineTimeSeconds: 1697122890,
        friendOfCount: 2,
        titlePhoto: "https://userpic.codeforces.org/3194164/title/236a114e65707c0c.jpg",
        handle: "mdalifahmed114510",
        avatar: "https://userpic.codeforces.org/3194164/avatar/e7fe851e5a6cdd45.jpg",
        registrationTimeSeconds: 1681143351
    },
    {
        contribution: 0,
        lastOnlineTimeSeconds: 1697121030,
        friendOfCount: 2,
        titlePhoto: "https://userpic.codeforces.org/3191873/title/7974a7f8b9d49983.jpg",
        handle: "hasan_03",
        avatar: "https://userpic.codeforces.org/3191873/avatar/2e0e68934a49a1ad.jpg",
        registrationTimeSeconds: 1681031521
    },
    {
        lastName: "Islam",
        lastOnlineTimeSeconds: 1697120947,
        rating: 879,
        friendOfCount: 2,
        titlePhoto: "https://userpic.codeforces.org/2547269/title/2105f79ec8d1b2b.jpg",
        handle: "learnerminj",
        avatar: "https://userpic.codeforces.org/2547269/avatar/2deb8063d2d872f0.jpg",
        firstName: "Md. Minhajul",
        contribution: 0,
        organization: "",
        rank: "newbie",
        maxRating: 990,
        registrationTimeSeconds: 1650537043,
        maxRank: "newbie"
    },
    {
        lastName: "Hasan",
        country: "Bangladesh",
        lastOnlineTimeSeconds: 1697139169,
        city: "Kishorganj",
        rating: 1192,
        friendOfCount: 68,
        titlePhoto: "https://userpic.codeforces.org/1996737/title/7603f6a0efe47acf.jpg",
        handle: "Heisenburg-120",
        avatar: "https://userpic.codeforces.org/1996737/avatar/580dc9910d898a.jpg",
        firstName: "Md. Rakibul",
        contribution: 0,
        organization: "Southeast University",
        rank: "newbie",
        maxRating: 1219,
        registrationTimeSeconds: 1616089486,
        maxRank: "pupil"
    },
    {
        lastName: "Haque",
        country: "Bangladesh",
        lastOnlineTimeSeconds: 1697138754,
        city: "Tāngāil",
        rating: 872,
        friendOfCount: 4,
        titlePhoto: "https://userpic.codeforces.org/3486978/title/5f4d420f8adeddf1.jpg",
        handle: "_Grandmaster",
        avatar: "https://userpic.codeforces.org/3486978/avatar/3588d7bff9410f77.jpg",
        firstName: "Md Imranul",
        contribution: 0,
        organization: "Hajee Mohammad Danesh Sci. and Tech. University",
        rank: "newbie",
        maxRating: 872,
        registrationTimeSeconds: 1695066247,
        maxRank: "newbie"
    },
    {
        lastName: "Islam",
        country: "Bangladesh",
        lastOnlineTimeSeconds: 1697124459,
        city: "Dhaka",
        rating: 403,
        friendOfCount: 3,
        titlePhoto: "https://userpic.codeforces.org/3191588/title/1f7f81127dee187e.jpg",
        handle: "Md-Merazul-Islam",
        avatar: "https://userpic.codeforces.org/3191588/avatar/590fbf9771ea4786.jpg",
        firstName: "Md Merazul",
        contribution: 0,
        organization: "Mymensing polytechic Institute",
        rank: "newbie",
        maxRating: 403,
        registrationTimeSeconds: 1681017401,
        maxRank: "newbie"
    },
    {
        lastName: "Hasan",
        country: "Bangladesh",
        lastOnlineTimeSeconds: 1697141754,
        city: "Rajshahi",
        rating: 925,
        friendOfCount: 14,
        titlePhoto: "https://userpic.codeforces.org/2851220/title/b65dc1a5aca9aa0d.jpg",
        handle: "mehadi40758",
        avatar: "https://userpic.codeforces.org/2851220/avatar/3d27fc67f5f915b8.jpg",
        firstName: "Md. Mehadi",
        contribution: 0,
        organization: "",
        rank: "newbie",
        maxRating: 926,
        registrationTimeSeconds: 1666061156,
        maxRank: "newbie"
    },
    {
        lastOnlineTimeSeconds: 1697109548,
        rating: 811,
        friendOfCount: 3,
        titlePhoto: "https://userpic.codeforces.org/2981561/title/50a6770fd4d8516f.jpg",
        handle: "mohiuddin_sizan",
        avatar: "https://userpic.codeforces.org/2981561/avatar/447c73302c060acc.jpg",
        firstName: "De_Vastator",
        contribution: 0,
        organization: "",
        rank: "newbie",
        maxRating: 811,
        registrationTimeSeconds: 1671701750,
        maxRank: "newbie"
    },
    {
        lastName: "TUHIN",
        country: "Bangladesh",
        lastOnlineTimeSeconds: 1697121070,
        city: "Natore",
        rating: 1059,
        friendOfCount: 34,
        titlePhoto: "https://userpic.codeforces.org/2556209/title/daa987e8df8aef2d.jpg",
        handle: "MOIN46",
        avatar: "https://userpic.codeforces.org/2556209/avatar/12bb07588760011.jpg",
        firstName: "MD MOIN UDDIN BHUIYAN",
        contribution: 0,
        organization: "Begum Rokeya University, Rangpur",
        rank: "newbie",
        maxRating: 1059,
        registrationTimeSeconds: 1650993500,
        maxRank: "newbie"
    },
    {
        lastName: "Alam",
        country: "Bangladesh",
        lastOnlineTimeSeconds: 1697121248,
        city: "Dhaka",
        rating: 390,
        friendOfCount: 2,
        titlePhoto: "https://userpic.codeforces.org/1951517/title/df3dfb3cbc82ae51.jpg",
        handle: "Morshed_Alam33",
        avatar: "https://userpic.codeforces.org/1951517/avatar/d33e7693be23d406.jpg",
        firstName: "Morshed",
        contribution: 0,
        organization: "Programing-Hero",
        rank: "newbie",
        maxRating: 390,
        registrationTimeSeconds: 1612866762,
        maxRank: "newbie"
    },
    {
        contribution: 0,
        lastOnlineTimeSeconds: 1697120982,
        friendOfCount: 2,
        titlePhoto: "https://userpic.codeforces.org/no-title.jpg",
        handle: "Mubarak_Hossain",
        avatar: "https://userpic.codeforces.org/no-avatar.jpg",
        registrationTimeSeconds: 1522600005
    },
    {
        lastName: "Sayem",
        country: "Bangladesh",
        lastOnlineTimeSeconds: 1697141619,
        city: "Dhaka",
        rating: 817,
        friendOfCount: 33,
        titlePhoto: "https://userpic.codeforces.org/2742743/title/cc0c69aefd0ea389.jpg",
        handle: "muhammad_sayem",
        avatar: "https://userpic.codeforces.org/2742743/avatar/5481c63ad5c09bb3.jpg",
        firstName: "Md Shahrul Islam",
        contribution: 0,
        organization: "Bangladesh University of Business and Technology",
        rank: "newbie",
        maxRating: 859,
        registrationTimeSeconds: 1661505233,
        maxRank: "newbie"
    },
    {
        lastName: "Muminur Rashid",
        country: "Bangladesh",
        lastOnlineTimeSeconds: 1697120377,
        city: "Sylhet",
        rating: 1095,
        friendOfCount: 9,
        titlePhoto: "https://userpic.codeforces.org/no-title.jpg",
        handle: "BLACK-HEAD",
        avatar: "https://userpic.codeforces.org/no-avatar.jpg",
        firstName: "Md",
        contribution: 0,
        organization: "Sylhet Engineering College",
        rank: "newbie",
        maxRating: 1095,
        registrationTimeSeconds: 1634924589,
        maxRank: "newbie"
    },
    {
        contribution: 0,
        lastOnlineTimeSeconds: 1697121476,
        organization: "Bangladesh University of Business and Technology",
        rating: 724,
        friendOfCount: 19,
        titlePhoto: "https://userpic.codeforces.org/2745547/title/3a4a121d801ba9fb.jpg",
        rank: "newbie",
        handle: "nasimahemd0909",
        maxRating: 829,
        avatar: "https://userpic.codeforces.org/2745547/avatar/16a7d5bea15e2d1b.jpg",
        registrationTimeSeconds: 1661649675,
        maxRank: "newbie"
    },
    {
        country: "Bangladesh",
        lastOnlineTimeSeconds: 1697107504,
        city: "Dhaka",
        rating: 397,
        friendOfCount: 2,
        titlePhoto: "https://userpic.codeforces.org/3191229/title/79eb26d14ce8bd20.jpg",
        handle: "MD.Naerullah",
        avatar: "https://userpic.codeforces.org/3191229/avatar/99015655c3fbf45c.jpg",
        firstName: "Nasrullah",
        contribution: 0,
        organization: "student",
        rank: "newbie",
        maxRating: 397,
        registrationTimeSeconds: 1680996123,
        maxRank: "newbie"
    },
    {
        lastName: "Niloy",
        country: "Bangladesh",
        lastOnlineTimeSeconds: 1697093172,
        city: "Dhaka",
        rating: 770,
        friendOfCount: 4,
        titlePhoto: "https://userpic.codeforces.org/2811047/title/e4a0d87f4c30c71b.jpg",
        handle: "niloy097",
        avatar: "https://userpic.codeforces.org/2811047/avatar/6d0e44b6e2f5bf9e.jpg",
        firstName: "Naeem Biswass",
        contribution: 0,
        organization: "City University, Bangladesh",
        rank: "newbie",
        maxRating: 770,
        registrationTimeSeconds: 1664538087,
        maxRank: "newbie"
    },
    {
        firstName: "Niloy",
        lastName: "Mahmud Apu",
        country: "Bangladesh",
        contribution: 0,
        lastOnlineTimeSeconds: 1697120626,
        organization: "Brahmanbaria Govt. College",
        friendOfCount: 8,
        titlePhoto: "https://userpic.codeforces.org/3190826/title/ab763104bf2f28b.jpg",
        handle: "niloymahmudapu",
        avatar: "https://userpic.codeforces.org/3190826/avatar/d53325a2e742e9fa.jpg",
        registrationTimeSeconds: 1680975252
    },
    {
        lastName: "Forazi",
        country: "Bangladesh",
        lastOnlineTimeSeconds: 1697120955,
        city: "Dhaka",
        rating: 358,
        friendOfCount: 3,
        titlePhoto: "https://userpic.codeforces.org/2576167/title/58c9f583f5a5d2d1.jpg",
        handle: "onceuponnion_9",
        avatar: "https://userpic.codeforces.org/2576167/avatar/dbf52042bf5f1c94.jpg",
        firstName: "MD. Nion",
        contribution: 0,
        organization: "Bangladesh University of Business and Technology",
        rank: "newbie",
        maxRating: 358,
        registrationTimeSeconds: 1652037232,
        maxRank: "newbie"
    },
    {
        lastName: "Nur",
        country: "Bangladesh",
        lastOnlineTimeSeconds: 1697115677,
        city: "Thākurgaon",
        rating: 689,
        friendOfCount: 8,
        titlePhoto: "https://userpic.codeforces.org/no-title.jpg",
        handle: "-11",
        avatar: "https://userpic.codeforces.org/no-avatar.jpg",
        firstName: "M.",
        contribution: 0,
        organization: "Islamic University,Bangladesh",
        rank: "newbie",
        maxRating: 947,
        registrationTimeSeconds: 1678476233,
        maxRank: "newbie"
    },
    {
        contribution: 0,
        lastOnlineTimeSeconds: 1697117150,
        rating: 1008,
        friendOfCount: 4,
        titlePhoto: "https://userpic.codeforces.org/2937574/title/a8d00332ea0e0f3a.jpg",
        rank: "newbie",
        handle: "Black_Pencil",
        maxRating: 1017,
        avatar: "https://userpic.codeforces.org/2937574/avatar/19d2e235825e35c4.jpg",
        registrationTimeSeconds: 1669897785,
        maxRank: "newbie"
    },
    {
        lastName: "Hassan",
        country: "Bangladesh",
        lastOnlineTimeSeconds: 1697127130,
        city: "Chittagong",
        rating: 805,
        friendOfCount: 10,
        titlePhoto: "https://userpic.codeforces.org/2681238/title/1da74bf3ed59d1cb.jpg",
        handle: "rakibulhassan29052000",
        avatar: "https://userpic.codeforces.org/2681238/avatar/e7cd3b8ea28ad495.jpg",
        firstName: "Rakibul",
        contribution: 0,
        organization: "Port City International University",
        rank: "newbie",
        maxRating: 819,
        registrationTimeSeconds: 1658080670,
        email: "rakibulhassan29052000@gmail.com",
        maxRank: "newbie"
    },
    {
        lastName: "Hasan",
        country: "Bangladesh",
        lastOnlineTimeSeconds: 1697134267,
        city: "Khulna",
        rating: 908,
        friendOfCount: 27,
        titlePhoto: "https://userpic.codeforces.org/2715662/title/6911937dfb7ea0e4.jpg",
        handle: "ratulhasan2108",
        avatar: "https://userpic.codeforces.org/2715662/avatar/b41c2b3c90e3b949.jpg",
        firstName: "Ratul",
        contribution: 0,
        organization: "BAUET",
        rank: "newbie",
        maxRating: 1155,
        registrationTimeSeconds: 1659984326,
        maxRank: "newbie"
    },
    {
        contribution: 0,
        lastOnlineTimeSeconds: 1697137019,
        friendOfCount: 3,
        titlePhoto: "https://userpic.codeforces.org/no-title.jpg",
        handle: "Rayhan_03",
        avatar: "https://userpic.codeforces.org/no-avatar.jpg",
        registrationTimeSeconds: 1680977172
    },
    {
        lastName: "Tonu",
        country: "Bangladesh",
        lastOnlineTimeSeconds: 1697057276,
        city: "Mymensingh",
        rating: 769,
        friendOfCount: 5,
        titlePhoto: "https://userpic.codeforces.org/no-title.jpg",
        handle: "sanzidtonu",
        avatar: "https://userpic.codeforces.org/no-avatar.jpg",
        firstName: "Rayhan",
        contribution: 0,
        organization: "Jatiya Kabi Kazi Nazrul Islam University",
        rank: "newbie",
        maxRating: 769,
        registrationTimeSeconds: 1655301792,
        maxRank: "newbie"
    },
    {
        lastName: "MEhedi",
        country: "Bangladesh",
        lastOnlineTimeSeconds: 1697129833,
        city: "Dhaka",
        rating: 795,
        friendOfCount: 6,
        titlePhoto: "https://userpic.codeforces.org/no-title.jpg",
        handle: "RiadMEhedi",
        avatar: "https://userpic.codeforces.org/no-avatar.jpg",
        firstName: "Riad",
        contribution: 0,
        organization: "University of Information Technology and Sciences",
        rank: "newbie",
        maxRating: 795,
        registrationTimeSeconds: 1676357951,
        maxRank: "newbie"
    },
    {
        lastName: "RIAD HOSSEN",
        country: "Bangladesh",
        lastOnlineTimeSeconds: 1697120713,
        city: "Dhaka",
        rating: 711,
        friendOfCount: 6,
        titlePhoto: "https://userpic.codeforces.org/no-title.jpg",
        handle: "robot_riad",
        avatar: "https://userpic.codeforces.org/no-avatar.jpg",
        firstName: "MD",
        contribution: 0,
        organization: "AIICT",
        rank: "newbie",
        maxRating: 773,
        registrationTimeSeconds: 1676274071,
        maxRank: "newbie"
    },
    {
        lastName: "Chowdhury",
        country: "Bangladesh",
        lastOnlineTimeSeconds: 1697116185,
        city: "Dhaka",
        rating: 946,
        friendOfCount: 6,
        titlePhoto: "https://userpic.codeforces.org/2922601/title/44687737647ef42e.jpg",
        handle: "Rocky20809",
        avatar: "https://userpic.codeforces.org/2922601/avatar/7b784391fecc61b2.jpg",
        firstName: "Rocky",
        contribution: 0,
        organization: "Prime University",
        rank: "newbie",
        maxRating: 946,
        registrationTimeSeconds: 1669298404,
        maxRank: "newbie"
    },
    {
        lastName: "Ahmed",
        country: "Bangladesh",
        lastOnlineTimeSeconds: 1697138975,
        city: "Sylhet",
        rating: 370,
        friendOfCount: 2,
        titlePhoto: "https://userpic.codeforces.org/3190886/title/e55ea8bd9b2d0bb3.jpg",
        handle: "rollno_infinity",
        avatar: "https://userpic.codeforces.org/3190886/avatar/fa0d11b26ea909.jpg",
        firstName: "Jakuan",
        contribution: 0,
        organization: "",
        rank: "newbie",
        maxRating: 370,
        registrationTimeSeconds: 1680976781,
        maxRank: "newbie"
    },
    {
        lastName: "Akter",
        country: "Bangladesh",
        lastOnlineTimeSeconds: 1697138069,
        rating: 778,
        friendOfCount: 7,
        titlePhoto: "https://userpic.codeforces.org/2932777/title/7958ee184b2fee79.jpg",
        handle: "S.Popy",
        avatar: "https://userpic.codeforces.org/2932777/avatar/7a9f9fc35d33189e.jpg",
        firstName: "Sharmin",
        contribution: 0,
        organization: "",
        rank: "newbie",
        maxRating: 822,
        registrationTimeSeconds: 1669694654,
        maxRank: "newbie"
    },
    {
        contribution: 0,
        lastOnlineTimeSeconds: 1697124931,
        rating: 1014,
        friendOfCount: 3,
        titlePhoto: "https://userpic.codeforces.org/2249179/title/2fa1ac896814c6ec.jpg",
        rank: "newbie",
        handle: "sadif609",
        maxRating: 1014,
        avatar: "https://userpic.codeforces.org/2249179/avatar/bd62aadce0832fef.jpg",
        registrationTimeSeconds: 1633685432,
        maxRank: "newbie"
    },
    {
        lastName: "Black",
        country: "Bangladesh",
        lastOnlineTimeSeconds: 1697115717,
        rating: 735,
        friendOfCount: 22,
        titlePhoto: "https://userpic.codeforces.org/2497828/title/c0780d0d57e0518e.jpg",
        handle: "samiunblack",
        avatar: "https://userpic.codeforces.org/2497828/avatar/80bd43a44be36d1f.jpg",
        firstName: "Samiun",
        contribution: 0,
        organization: "",
        rank: "newbie",
        maxRating: 865,
        registrationTimeSeconds: 1647494780,
        maxRank: "newbie"
    },
    {
        lastName: "Sadik Khan",
        country: "Bangladesh",
        lastOnlineTimeSeconds: 1697048112,
        city: "Dhaka",
        rating: 1026,
        friendOfCount: 7,
        titlePhoto: "https://userpic.codeforces.org/2718895/title/1e33fcfea1ccd1d7.jpg",
        handle: "SSKsan",
        avatar: "https://userpic.codeforces.org/2718895/avatar/b82ed61a83ac096f.jpg",
        firstName: "Samin",
        contribution: 0,
        organization: "Prime University",
        rank: "newbie",
        maxRating: 1026,
        registrationTimeSeconds: 1660202557,
        maxRank: "newbie"
    },
    {
        lastName: "Karim",
        country: "Bangladesh",
        lastOnlineTimeSeconds: 1697088035,
        city: "Comilla",
        rating: 1071,
        friendOfCount: 23,
        titlePhoto: "https://userpic.codeforces.org/3090759/title/b2159c26f2965124.jpg",
        handle: "schrodingersmile",
        avatar: "https://userpic.codeforces.org/3090759/avatar/cbc5eddafcd1dc64.jpg",
        firstName: "Sarafat",
        contribution: 0,
        organization: "Khulna University",
        rank: "newbie",
        maxRating: 1124,
        registrationTimeSeconds: 1676690838,
        maxRank: "newbie"
    },
    {
        contribution: 0,
        lastOnlineTimeSeconds: 1697087051,
        friendOfCount: 2,
        titlePhoto: "https://userpic.codeforces.org/no-title.jpg",
        handle: "shafaitzaman1234",
        avatar: "https://userpic.codeforces.org/no-avatar.jpg",
        registrationTimeSeconds: 1684081621
    },
    {
        contribution: 0,
        lastOnlineTimeSeconds: 1697134787,
        rating: 813,
        friendOfCount: 3,
        titlePhoto: "https://userpic.codeforces.org/2462697/title/f181c6b551788c85.jpg",
        rank: "newbie",
        handle: "shafiq1st",
        maxRating: 813,
        avatar: "https://userpic.codeforces.org/2462697/avatar/f92b32a307578863.jpg",
        registrationTimeSeconds: 1645380661,
        maxRank: "newbie"
    },
    {
        lastName: "Moaz",
        country: "Bangladesh",
        lastOnlineTimeSeconds: 1697121003,
        city: "Dhaka",
        rating: 861,
        friendOfCount: 5,
        titlePhoto: "https://userpic.codeforces.org/2774297/title/e6af55c675528681.jpg",
        handle: "makmodol1173",
        avatar: "https://userpic.codeforces.org/2774297/avatar/a3d6a8aa8a7955e7.jpg",
        firstName: "Shah",
        contribution: 0,
        organization: "",
        rank: "newbie",
        maxRating: 861,
        registrationTimeSeconds: 1662824104,
        maxRank: "newbie"
    },
    {
        lastName: "Islam",
        country: "Bangladesh",
        lastOnlineTimeSeconds: 1697120429,
        city: "Dhaka",
        rating: 367,
        friendOfCount: 2,
        titlePhoto: "https://userpic.codeforces.org/3191558/title/ff27a3c17e898469.jpg",
        handle: "sharif_dupharma",
        avatar: "https://userpic.codeforces.org/3191558/avatar/3974fa683fe96e4b.jpg",
        firstName: "Md Shariful",
        contribution: 0,
        organization: "University of Dhaka",
        rank: "newbie",
        maxRating: 367,
        registrationTimeSeconds: 1681015986,
        maxRank: "newbie"
    },
    {
        contribution: 0,
        lastOnlineTimeSeconds: 1697140534,
        rating: 819,
        friendOfCount: 5,
        titlePhoto: "https://userpic.codeforces.org/2244093/title/21f3c9215a4670d2.jpg",
        rank: "newbie",
        handle: "Mistake_factory",
        maxRating: 986,
        avatar: "https://userpic.codeforces.org/2244093/avatar/dbd261052151242.jpg",
        registrationTimeSeconds: 1633462435,
        maxRank: "newbie"
    },
    {
        country: "Bangladesh",
        lastOnlineTimeSeconds: 1697130327,
        city: "Dhaka",
        rating: 633,
        friendOfCount: 17,
        titlePhoto: "https://userpic.codeforces.org/2793442/title/a8311ec8c4644ba4.jpg",
        handle: "CRYP70N1C",
        avatar: "https://userpic.codeforces.org/2793442/avatar/e2a942fc182f4fbb.jpg",
        contribution: 0,
        organization: "Bangladesh University of Business and Technology",
        rank: "newbie",
        maxRating: 922,
        registrationTimeSeconds: 1663704998,
        maxRank: "newbie"
    },
    {
        lastName: "Hridoy",
        country: "Bangladesh",
        lastOnlineTimeSeconds: 1697134297,
        city: "Dhaka",
        rating: 825,
        friendOfCount: 13,
        titlePhoto: "https://userpic.codeforces.org/3335329/title/375d1249906547c4.jpg",
        handle: "BugBane_Hridoy",
        avatar: "https://userpic.codeforces.org/3335329/avatar/9daeec8c87f0f08f.jpg",
        firstName: "MD.Mahbubur Rahman",
        contribution: 0,
        organization: "Bangladesh University of Business and Technology",
        rank: "newbie",
        maxRating: 825,
        registrationTimeSeconds: 1688818277,
        maxRank: "newbie"
    },
    {
        lastName: "Islam",
        country: "Bangladesh",
        lastOnlineTimeSeconds: 1697120825,
        city: "Pābna",
        rating: 713,
        friendOfCount: 20,
        titlePhoto: "https://userpic.codeforces.org/2663924/title/ace9e5bec0a118b1.jpg",
        handle: "b14ckb3rry",
        avatar: "https://userpic.codeforces.org/2663924/avatar/8718d0c6e1d08482.jpg",
        firstName: "Md. Sirajul",
        contribution: 0,
        organization: "BAUET",
        rank: "newbie",
        maxRating: 829,
        registrationTimeSeconds: 1657011348,
        maxRank: "newbie"
    },
    {
        contribution: 0,
        lastOnlineTimeSeconds: 1697112326,
        friendOfCount: 2,
        titlePhoto: "https://userpic.codeforces.org/no-title.jpg",
        handle: "soaib056",
        avatar: "https://userpic.codeforces.org/no-avatar.jpg",
        registrationTimeSeconds: 1681014903
    },
    {
        lastName: "Hasan",
        country: "Bangladesh",
        lastOnlineTimeSeconds: 1697121098,
        city: "Narsingdi",
        rating: 716,
        friendOfCount: 6,
        titlePhoto: "https://userpic.codeforces.org/no-title.jpg",
        handle: "Soumick",
        avatar: "https://userpic.codeforces.org/no-avatar.jpg",
        firstName: "MD. Asraful",
        contribution: 0,
        organization: "Green University Of Bangladesh",
        rank: "newbie",
        maxRating: 716,
        registrationTimeSeconds: 1680972389,
        maxRank: "newbie"
    },
    {
        lastName: "Srayo",
        country: "Bangladesh",
        lastOnlineTimeSeconds: 1697134301,
        city: "Dhaka",
        rating: 376,
        friendOfCount: 6,
        titlePhoto: "https://userpic.codeforces.org/3188459/title/488434b848df0ed1.jpg",
        handle: "srayosikder",
        avatar: "https://userpic.codeforces.org/3188459/avatar/9d4fee781653a7f0.jpg",
        firstName: "Md. Saimon Sikder",
        contribution: 0,
        organization: "Bangladesh University of Business and Technology",
        rank: "newbie",
        maxRating: 376,
        registrationTimeSeconds: 1680864446,
        maxRank: "newbie"
    },
    {
        lastName: "Chandra Singha",
        country: "Bangladesh",
        lastOnlineTimeSeconds: 1697102283,
        city: "Rangpur City",
        rating: 861,
        friendOfCount: 24,
        titlePhoto: "https://userpic.codeforces.org/2708366/title/9b4e145623295421.jpg",
        handle: "sumit_chandra",
        avatar: "https://userpic.codeforces.org/2708366/avatar/32c43ba5ec73a368.jpg",
        firstName: "Sumit",
        contribution: 0,
        organization: "Begum Rokeya University, Rangpur",
        rank: "newbie",
        maxRating: 898,
        registrationTimeSeconds: 1659552745,
        maxRank: "newbie"
    },
    {
        lastName: "Akter",
        country: "Bangladesh",
        lastOnlineTimeSeconds: 1697121230,
        city: "Dhaka",
        rating: 863,
        friendOfCount: 5,
        titlePhoto: "https://userpic.codeforces.org/no-title.jpg",
        handle: "Sunjida_Akter",
        avatar: "https://userpic.codeforces.org/no-avatar.jpg",
        firstName: "Sunjida",
        contribution: 0,
        organization: "",
        rank: "newbie",
        maxRating: 919,
        registrationTimeSeconds: 1643990782,
        maxRank: "newbie"
    },
    {
        lastName: "Gulnaj",
        country: "Bangladesh",
        lastOnlineTimeSeconds: 1697118080,
        city: "Sylhet",
        rating: 915,
        friendOfCount: 22,
        titlePhoto: "https://userpic.codeforces.org/no-title.jpg",
        handle: "SyedaGulnaj",
        avatar: "https://userpic.codeforces.org/no-avatar.jpg",
        firstName: "Syeda",
        contribution: 0,
        organization: "Sylhet Engineering College",
        rank: "newbie",
        maxRating: 1389,
        registrationTimeSeconds: 1568470318,
        maxRank: "pupil"
    },
    {
        firstName: "Tahdi",
        lastName: "Islam",
        country: "Bangladesh",
        contribution: 0,
        lastOnlineTimeSeconds: 1697130325,
        city: "Lakshmīpur",
        organization: "Phitron",
        friendOfCount: 2,
        titlePhoto: "https://userpic.codeforces.org/3451959/title/359e09adcd136483.jpg",
        handle: "tahdiislam",
        avatar: "https://userpic.codeforces.org/3451959/avatar/c302151ed10bceff.jpg",
        registrationTimeSeconds: 1693872306
    },
    {
        lastName: "Ferdous",
        country: "Bangladesh",
        lastOnlineTimeSeconds: 1697093025,
        city: "Dhaka",
        rating: 847,
        friendOfCount: 5,
        titlePhoto: "https://userpic.codeforces.org/3095396/title/d9c9b260923d8d56.jpg",
        handle: "tahsin005",
        avatar: "https://userpic.codeforces.org/3095396/avatar/1032423c67de0a02.jpg",
        firstName: "MD. Tahsin",
        contribution: 0,
        organization: "City University, Bangladesh",
        rank: "newbie",
        maxRating: 847,
        registrationTimeSeconds: 1676921590,
        maxRank: "newbie"
    },
    {
        firstName: "Md Talat Mahmud",
        lastName: "Tomal",
        contribution: 0,
        lastOnlineTimeSeconds: 1697120703,
        organization: "",
        friendOfCount: 2,
        titlePhoto: "https://userpic.codeforces.org/2895665/title/a7c3870848acbec2.jpg",
        handle: "talatmcc",
        avatar: "https://userpic.codeforces.org/2895665/avatar/f612f78e8e6f9310.jpg",
        registrationTimeSeconds: 1668101289
    },
    {
        contribution: 0,
        lastOnlineTimeSeconds: 1697120666,
        friendOfCount: 1,
        titlePhoto: "https://userpic.codeforces.org/no-title.jpg",
        handle: "voidd_nulll",
        avatar: "https://userpic.codeforces.org/no-avatar.jpg",
        registrationTimeSeconds: 1695542132
    }
]

// https://codechef-cards-api.onrender.com/{username}
export const codeChefUsers: CodeChefUser[] = [
    {
        username: "aminu_ldola",
        name: "Md. Aminul Islam",
        isActiveUser: true,
        rating: 1086,
        highestRating: 1086,
        stars: 1,
        globalRank: 115142,
        countryRank: 2883,
        problemFullySolved: 0,
        problemPartiallySolved: 0,
        contestParticipated: 1,
        country: "Bangladesh"
    },
    {
        username: "niloymahmudapu",
        name: "Niloy Mahmud Apu",
        isActiveUser: true,
        rating: 1456,
        highestRating: 1456,
        stars: 2,
        globalRank: 36421,
        countryRank: 1071,
        problemFullySolved: 0,
        problemPartiallySolved: 0,
        contestParticipated: 2,
        country: "Bangladesh"
    },
    {
        username: "void_null",
        name: "F.F.F",
        isActiveUser: false,
        rating: 1380,
        highestRating: 1380,
        stars: 1,
        globalRank: null,
        countryRank: null,
        problemFullySolved: 0,
        problemPartiallySolved: 0,
        contestParticipated: 2,
        country: "India"
    }
]